version: 2
updates:
  # 1️⃣ Terraform updates
  - package-ecosystem: "terraform"
    directory: "/vpc"
    target-branch: "main"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "GMT"
    reviewers:
      - "nanafilbert"
