version: 2
updates:
  - package-ecosystem: "Terraform"
    directory: "/"
    target-branch: "main"
    reviewers:
      - "nanafilbert"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "GMT"
   