
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform_aws_module/modules/vpc"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "terraform"
    directory: "/terraform_aws_module/modules/ec2"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "terraform"
    directory: "/terraform_aws_module/modules/security_grps"
    schedule:
      interval: "weekly"
    reviewers:
      - "nanafilbert"
