name: Version Bump & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 give GITHUB_TOKEN push access

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "Current version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determine new version
        id: bump_version
        run: |
          VERSION=$(cat VERSION)
          IFS='.' read -r -a parts <<< "$VERSION"
          parts[2]=$((parts[2] + 1))  # Increment patch
          NEW_VERSION="${parts[0]}.${parts[1]}.${parts[2]}"
          echo "$NEW_VERSION" > VERSION
          echo "New version will be $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push new version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}" || echo "No changes to commit"
          git tag "v${{ steps.bump_version.outputs.new_version }}"
          git push origin main --tags

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.bump_version.outputs.new_version }}"
          name: "Release ${{ steps.bump_version.outputs.new_version }}"
          body: "Automated release for version ${{ steps.bump_version.outputs.new_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}