name: Bump version
on:
  push:
    branches:
      - main
    paths: 
      - "terraform_aws_module/modules/**"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Try built-in token first
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          DRY_RUN: false

      - name: Debug output
        run: |
          echo "Previous tag: ${{ steps.bump-version.outputs.tag }}"
          echo "New tag: ${{ steps.bump-version.outputs.new_tag }}"