name: Diagnostic
on:
  push:
    branches:
      - main

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: List repository structure
        run: |
          echo "Repository structure:"
          find . -type f -name "*.tf" -o -name "*.yml" -o -name "*.yaml" | head -20
          
      - name: Check current branch
        run: |
          echo "Current branch: $(git branch --show-current)"
          
      - name: List changed files in last commit
        run: |
          echo "Files changed in last commit:"
          git diff-tree --no-commit-id --name-only -r HEAD