name: Bump version
on:
  push:
    branches:
    - main
    paths: 
    - "terraform_aws_module/modules/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false


    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: success()
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
          tag_name: ${{ steps.bump-version.outputs.new_tag }}
          name: Release ${{ steps.bump-version.outputs.new_tag }}
          generate_release_notes: true
